# Site settings
title: east5th - blog
email: hello@east5th.co
description: "East5th provides consulting services and educational resources for building secure, robust, maintainable web applications. We’re constantly striving to deliver the highest quality articles, tools, services, and resources related to software development, software security, and consulting."
baseurl: ""
url: "http://www.east5th.co"
twitter_username: petecorey
github_username:  pcorey

paginate: 3
paginate_path: "/blog/:num/"

# Build settings
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title/"

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - node_modules
  - less
