# Site settings
title: east5th - blog
email: hello@east5th.co
description: "Pete Corey's soapbox for shouting about computers and things."
baseurl: ""
url: "http://blog.east5th.co"
twitter_username: petecorey
github_username:  pcorey

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap

exclude:
  - node_modules
  - less