# Site settings
title: 1pxsolidtomato
email: hello@1pxsolidtomato.com
description: "Pete Corey's soapbox for shouting about computers and things."
baseurl: ""
url: "http://1pxsolidtomato.com"
twitter_username: petecorey
github_username:  pcorey

# Build settings
markdown: kramdown
permalink: pretty
