# Site settings
title: east5th - blog
email: hello@east5th.co
description: "Meteor software development and security."
baseurl: ""
url: "http://blog.east5th.co"
twitter_username: petecorey
github_username:  pcorey

paginate: 5
paginate_path: "/:num/"

featured_posts: [
  ""
]

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - node_modules
  - less
