# Site settings
title: east5th - blog
email: hello@east5th.co
description: "Meteor software development and security."
baseurl: ""
url: "http://blog.east5th.co"
twitter_username: petecorey
github_username:  pcorey

paginate: 3
paginate_path: "/blog/:num/"

# Build settings
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title/"

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - node_modules
  - less
