# Site settings
title: Pete Corey
description: "Pete Corey is an independent consultant, web developer, and writer based out of Denver, Colorado. He writes weekly articles on software development and his eternal quest to build Cool Stuff™."
baseurl: ""
url: "http://www.petecorey.com"
twitter_username: petecorey
github_username:  pcorey

defaults:
  - scope:
      path: ""
    values:
      image: "/img/Pete and Lyra Square 300x300.png"

paginate: 3
paginate_path: "/blog/:num/"

future: true

# Build settings
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - node_modules
  - less
