# Site settings
title: Pete Corey
description: "Pete Corey is an independent consultant, writer, and web developer based out of Chattanooga, Tennessee. He writes weekly articles on software development and his eternal quest to build Cool Stuff™."
baseurl: ""
url: "http://www.petecorey.com"
twitter_username: petecorey
github_username:  pcorey

defaults:
  - scope:
      path: ""
    values:
      image: /img/portrait-150x150.png

paginate: 3
paginate_path: "/blog/:num/"

# Build settings
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title/"

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - node_modules
  - less
